return {
    "williamboman/mason-lspconfig.nvim",
    opts = {
        ensure_installed = {
            "clangd",
            "neocmake",
            "rust_analyzer",
            "pyright",
            "ruff_lsp",
            "taplo",
            "cssls",
            "html",
            "sumneko_lua",
            "tsserver",
            "denols",
            "emmet_ls",
            "cssls",
            "marksman",
            "jsonls",
            "yamlls",
            "sqlls",
            "bashls",
        },
    },
}
